[2025-03-30T17:14:29.272+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-30T17:14:29.289+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_deliverable.publish_csv manual__2025-03-30T17:13:24.172060+00:00 [queued]>
[2025-03-30T17:14:29.293+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_deliverable.publish_csv manual__2025-03-30T17:13:24.172060+00:00 [queued]>
[2025-03-30T17:14:29.293+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-03-30T17:14:29.305+0000] {taskinstance.py:2330} INFO - Executing <Task(ProduceToTopicOperator): publish_csv> on 2025-03-30 17:13:24.172060+00:00
[2025-03-30T17:14:29.311+0000] {standard_task_runner.py:64} INFO - Started process 275 to run task
[2025-03-30T17:14:29.314+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_deliverable', 'publish_csv', 'manual__2025-03-30T17:13:24.172060+00:00', '--job-id', '114', '--raw', '--subdir', 'DAGS_FOLDER/dag_deliverable.py', '--cfg-path', '/tmp/tmp4x27yyvh']
[2025-03-30T17:14:29.315+0000] {standard_task_runner.py:91} INFO - Job 114: Subtask publish_csv
[2025-03-30T17:14:29.345+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_deliverable.publish_csv manual__2025-03-30T17:13:24.172060+00:00 [running]> on host airflow
[2025-03-30T17:14:29.392+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_deliverable' AIRFLOW_CTX_TASK_ID='publish_csv' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T17:13:24.172060+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-30T17:13:24.172060+00:00'
[2025-03-30T17:14:29.393+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-30T17:14:29.408+0000] {base.py:84} INFO - Using connection ID 'kafka_default' for task execution.
[2025-03-30T17:14:29.414+0000] {produce.py:41} INFO - Producer <cimpl.Producer object at 0x7f144d6ffd60>
[2025-03-30T17:14:29.417+0000] {dag_deliverable.py:59} ERROR - ‚ùå Error al leer el archivo: [Errno 2] No such file or directory: '/opt/airflow/home_temperature_and_humidity_smoothed_filled.csv'
[2025-03-30T17:14:29.417+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-30T17:14:29.418+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/kafka/operators/produce.py", line 126, in execute
    for k, v in producer_callable():
  File "/opt/airflow/dags/dag_deliverable.py", line 52, in publish_csv
    with open(
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/home_temperature_and_humidity_smoothed_filled.csv'
[2025-03-30T17:14:29.423+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_deliverable, task_id=publish_csv, run_id=manual__2025-03-30T17:13:24.172060+00:00, execution_date=20250330T171324, start_date=20250330T171429, end_date=20250330T171429
[2025-03-30T17:14:29.435+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 114 for task publish_csv ([Errno 2] No such file or directory: '/opt/airflow/home_temperature_and_humidity_smoothed_filled.csv'; 275)
[2025-03-30T17:14:29.446+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-03-30T17:14:29.456+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T17:14:29.457+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
